### ISSUE TITLE
Add a conditional imagePullSecrets

### ISSUE THREAD

**Issue by thibaud-socrate** [bakito/vault-unsealer#162]
Hello,
Firstly thank you for the project it is really useful for us.
Can you add a conditional `imagePullSecrets` in `template.spec` https://github.com/bakito/vault-unsealer/blob/main/chart/templates/deployment.yaml#L26 like the one they are doing in the following helm (we need to define some extra code) to make it work for us https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/default-backend-deployment.yaml#L42-L44
If you want we already have the code and would be glad to do a PR.

**Comment by bakito** [comment]
Hi @thibaud-socrate 

Thank you very much for the request.
Any pull request is welcome, if you alrwady have the solution.
